name: deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            npmCacheDirectory: ${{ steps.npm-cache.outputs.npmCacheDirectory }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - run: npm ci --prefer-offline --no-audit --progress=false

            # Cache node_modules
            - name: Get npm cache directory
              id: npm-cache
              run: |
                echo "::set-output name=npmCacheDirectory::$(npm config get cache)"
            - name: Cache .npm directory
              uses: actions/cache@v2
              with:
                  path: ${{ steps.npm-cache.outputs.npmCacheDirectory }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-
            - name: Cache node_modules directory
              id: cache-node_modules
              uses: actions/cache@v2.0.0
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node_modules

            - run: npm test -- --ci

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            # Cache node_modules
            - name: Cache .npm directory
              uses: actions/cache@v2
              with:
                  path: ${{ needs.build.outputs.npmCacheDirectory }}
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
            - name: Cache node_modules
              id: cache-node_modules
              uses: actions/cache@v2.0.0
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

            - name: Vercel
              run: |
                npm i -g vercel
                vercel --prod --confirm -t ${{ secrets.VERCEL_TOKEN }} -m githubCommitSha=${{ github.sha }} -m githubCommitAuthorName=${{ github.actor }} githubRepo=${{ github.repository }} -m githubCommitRepo=${{ github.repository }}
